version: "3.8"

services:
  api-client:
    build:
      context: .
      dockerfile: docker/Dockerfile.api-client
    ports:
      - "${API_CLIENT_PORT}:3000"
    env_file:
      - .env
    restart: always

  mock-factory:
    build:
      context: .
      dockerfile: docker/Dockerfile.mock-factory
    ports:
      - "${MOCK_FACTORY_PORT}:80"
    env_file:
      - .env
    restart: always

networks:
  default:
    name: dev-tool
