import type { Metadata } from "next";
import "./globals.css";
import { Public_Sans } from "next/font/google";
import { WorkspaceProvider } from "@/contexts/WorkspaceContext";

// 폰트 설정
const publicSans = Public_Sans({
  subsets: ["latin"],
  weight: ["400", "600", "700", "900"],
  style: ["normal", "italic"],
  variable: "--font-public-sans",
});

export const metadata: Metadata = {
  title: "API Client",
  description: "Generated by API Client",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={publicSans.variable}>
      <body className={`${publicSans.className} antialiased`}>
        <WorkspaceProvider>{children}</WorkspaceProvider>
      </body>
    </html>
  );
}
